# Generated by Django 4.1.2 on 2022-10-31 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="description",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="thing",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="thing",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
