# Generated by Django 4.1.2 on 2022-10-31 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0002_alter_thing_description_alter_thing_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
